server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://rm-bp1tgrr6l8vxak63nko.mysql.rds.aliyuncs.com:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: Yzjhaha123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql打印